### PR TITLE
Library update for MobX >= 4

### PR DESCRIPTION
**Pull request by laszloKajan**
I'm using this library with MobX 4 now, with the suggested changes.
Comments are most welcome.

### CODE REVIEW

**Comment by laszloKajan** [comment]
@machwitt So, Martin, how can we move forward to MobX 4?
I'm using this branch for production for a while, and it's all right.

**Comment by machwitt** [comment]
@laszloKajan @geekflyer 
Hi Laszlo Mobx4 update is a major change and I think Christian Theilemann should approve that. It should be marked by increasing the major version in package.json

@geekflyer Christian, can you please take a look?

**Comment by laszloKajan** [comment]
@machwitt I got the impression that Christian was no longer actively maintaining this repo, given he left SAP. That's why I wanna work with you closely. But if you/we can get Christian's opinion, so much the better!

**Comment by laszloKajan** [comment]
@martinxxD Hello Martin! Congratulations on your project ownership. What do you think about this pull request, for MobX >= 4? I would appreciate your review and comments. Best regards, Laszlo

**Review by martwz — APPROVED** [review]
@laszloKajan thanks for your contributions, this looks good to me, merging this!

**Pull request merged**
